name: Deploy with GH Actions to make use of Sass

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v4
      - name: Setting up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Building CSS with Sass
        run: npm run sass:build
      - name: Copying index.html to dist folder
        run: cp index.html dist/
      - name: Running ls to make sure everything works
        run: ls dist
      # - name: Setting up Pages
      #   uses: actions/configure-pages@v3
      # - name: Uploading artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: "./dist"
      # - name: Deploying to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1